In [ ]:
import pandas as pd
import numpy as np
print("Intermediate Pandas Exercise")
print("Complete each task by writing the requested Pandas code.")
# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\nTask 1: Basic Pandas Functions and Converting Arrays to DataFrames")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.
# Your code for Task 1 here:
# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])
print("s1_1:")
print(s1_1)
# 1.2 Create a 3x4 NumPy array with random integers between 1 and 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
print("np_array1_2:")
print(np_array1_2)
# 1.3 Convert the NumPy array into a Pandas DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])
print("df1_3:")
print(df1_3)

# Task 2: Synthetic Data Generation for Practice
# - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# - 'Sales': Random integers between 100 and 1000.
# - 'Quantity': Random integers between 1 and 10.
# - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.
# Your code for Task 2 here:
# Task 2: Synthetic Data Generation for Practice
print("\nTask 2: Synthetic Data Generation for Practice")
# Create the DataFrame
df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', end='2023-04-10')[:100],
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100),
    'Quantity': np.random.randint(1, 11, 100)
})
# Introduce 5 random NaN values in the Sales column
sales_nan = np.random.choice(df_sales.index, 5, replace=False)
df_sales.loc[sales_nan, 'Sales'] = np.nan
# Introduce 3 random NaN values in the Quantity column
quantity_nan = np.random.choice(df_sales.index, 3, replace=False)
df_sales.loc[quantity_nan, 'Quantity'] = np.nan
# Display the DataFrame
print(df_sales)


# Task 3: Indexing and Slicing in DataFrames
print("\nTask 3: Indexing and Slicing in DataFrames")
# Use 'df_sales' from Task 2.
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.
# Your code for Task 3 here:
# Task 3: Indexing and Slicing in DataFrames
# Task 3: Indexing and Slicing in DataFrames
df3_1 = df_sales[['Region', 'Sales']]
print(df3_1)
# 3.2 Select rows where 'Product' is 'Laptop'
df3_2 = df_sales[df_sales['Product'] == 'Laptop']
print(df3_2)
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]
print(df3_3)
# 3.4 Select the 'Sales' value for the first 'Monitor'
val3_4 = df_sales.loc[df_sales['Product'] == 'Monitor', 'Sales'].iloc[0]
print(val3_4)


# Task 4: Data Cleaning (Handling Missing Values)
print("\nTask 4: Data Cleaning (Handling Missing Values)")
# Use 'df_sales' from Task 2 (which should have NaNs).
# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.
# Your code for Task 4 here:
# Task 4: Data Cleaning (Handling Missing Values)
# 4.1 Count missing values in each column
missing_counts4_1 = df_sales.isnull().sum()
print("Missing values in each column:")
print(missing_counts4_1)
# 4.2 Fill missing Sales values with the mean of the Sales column
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean())
print("\nDataFrame after filling missing Sales values:")
print(df4_2_filled)
# 4.3 Drop rows that have any missing values
df4_3_dropped = df_sales.dropna()
print("\nDataFrame after dropping rows with missing values:")
print(df4_3_dropped)

# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n Task 5: Data Manipulation (Columns, Sorting, Grouping)")
# Use 'df_sales' (the original one with NaNs)
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
#     Store the result in 'df5_3_grouped_region'.
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
#     Store the result in 'df5_4_grouped_product'.
# Your code for Task 5 here:
# 5.1 Create a new column 'Total_Revenue'
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']
print("df_sales with Total_Revenue:")
print(df_sales)
# 5.2 Sort by Date (ascending) and Sales (descending)
df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])
print("df5_2_sorted:")
print(df5_2_sorted)
# 5.3 Group by Region and calculate the sum of Sales and Quantity
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()
print("df5_3_grouped_region:")
print(df5_3_grouped_region)
# 5.4 Group by Product and calculate the average Sales
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()
print("df5_4_grouped_product:")
print(df5_4_grouped_product)


Intermediate Pandas Exercise
Complete each task by writing the requested Pandas code.

Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64
np_array1_2:
[[69 97 81 15]
 [32 60 46 38]
 [17 92 80 27]]
df1_3:
    A   B   C   D
0  69  97  81  15
1  32  60  46  38
2  17  92  80  27

Task 2: Synthetic Data Generation for Practice
         Date Region   Product  Sales  Quantity
0  2023-01-01   East    Laptop  272.0       7.0
1  2023-01-02   West   Monitor  750.0       5.0
2  2023-01-03  South  Keyboard  985.0       8.0
3  2023-01-04  South   Monitor  547.0       2.0
4  2023-01-05  South    Laptop  119.0       9.0
..        ...    ...       ...    ...       ...
95 2023-04-06  North  Keyboard  516.0      10.0
96 2023-04-07  South  Keyboard  822.0       7.0
97 2023-04-08  South   Monitor  420.0       4.0
98 2023-04-09   West     Mouse  672.0      10.0
99 2023-04-10   East   Monitor  369.0       4.0

[100 rows x 5 columns]

